### ISSUE TITLE
Database updates

### ISSUE THREAD

**Issue by lonix1** [soenneker/soenneker.validators.email.disposable.online#1031]
Hi @soenneker and thanks for making and maintaining this library! Just what I was looking for.

Regarding the [list of domains](https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.json): what is the source, and how often is it updated?

I want to know whether I can just integrate this library into my system and then "forget about it"?

**Comment by soenneker** [comment]
Hi @lonix1, the source is https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.json if you don't set it yourself. It's configurable. It is set it and forget it.

However, I only recommend this package if you don't update NuGet packages much at all. I have another package (see readme) that is more resilient to network issues etc.

The other package is updated daily from that list above.
